name: Build and push Docker image
on:
  push:
    branches: [ master ]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.10.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: viplab/websocket-api
        tags: latest
        dockerfile: Dockerfile.jvm
        add_git_labels: true
